version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
  db:
    platform: linux/amd64
    image: mcr.microsoft.com/mssql/server:latest
    container_name: my_mssql_db 
    ports:
      - "1433:1433"  
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: strongyPassword123